# Generated by Django 3.2.8 on 2021-10-27 19:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_rename_descriprion_review_descriprtion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='descriprtion',
            new_name='description',
        ),
    ]
